pine_sap/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from pine_sap.forms import UserLoginForm
from pine_sap.models import User, db
from werkzeug.security import check_password_hash

from flask_login import login_user, logout_user, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET','POST'])
def signup():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            print(email, username, password)

            user = User(email, username, password=password)

            db.session.add(user)
            db.session.commit()

            flash(f"You have created a user acount {username}, user-created")

            return redirect(url_for('auth.signin'))
        
    except:
        raise Exception('Invalid Form Data: Please change your form')

    return render_template('signup.html', form=form)


@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email,password)


            logged_user = User.query.filter(User.email == email).first()
            print(logged_user)
            if logged_user and check_password_hash(logged_user.password, password):
                print(f"this is the logged user {logged_user}")
                login_user(logged_user)
                flash(f"You were successfuly logged in Via: email/password", 'auth-success')
                return redirect(url_for('site.profile'))
            else:
                flash("Your email/password is incurect", 'auth-failed')
                return redirect(url_for('auth.signin'))

    except:
        raise Exception('Invalid Form Data: Please Check Your Form!')

    return render_template('/signin.html', form=form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

pine_sap/site/routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user
from pine_sap.forms import ArtistForm
from pine_sap.models import Artist, db

"""
    Note that in the below code,
    some arguments are specified when creating Blueprint objects.
    The first argument, 'site' is the Blueprint's name,
    which flask uses for routing.
    The second argument, __name__,  is the Blueprint's import name, 
    which flask uses to locate the Blueprint's resources
"""

site = Blueprint('site', __name__, template_folder = 'site_templates')

@site.route('/')
def home():
    print("this is inside of site.routes")
    return render_template('index.html')

@site.route('/profile', methods=['GET', 'POST'])
@login_required

def profile():
    my_artist = ArtistForm() # data coming back from the forms

    try:
        print('inside TRY: site/routes')
        if request.method == "POST" and my_artist.validate_on_submit():
            your_name = my_artist.your_name.data
            artist_name = my_artist.artist_name.data
            description = my_artist.description.data
            fav_song = my_artist.fav_song.data
            artist_rating = my_artist.artist_rating.data
            user_token = current_user.token

            artist = Artist(your_name, artist_name, description, artist_rating, fav_song, user_token)

            db.session.add(artist)
            db.session.commit()
            print('Should be in database')
            return redirect(url_for('site.profile'))

    except:
        raise Exception('Artist Not Created: please check form again')
    print('missed exception')
    current_user_token = current_user.token

    artists = Artist.query.filter_by(user_token=current_user_token)
    return render_template('profile.html', form=my_artist, artists= artists)

pine_sap/templates/artist_form.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="your_name-field">
            {{ form.your_name.label }}
            {{ form.your_name(class = "form-control", placeholder="Your Name") }}
        </fieldset>
        <fieldset id="artist_name-field">
            {{ form.artist_name.label }}
            {{ form.artist_name(class = "form-control", placeholder="Artist Name") }}
        </fieldset>
        <fieldset id="description-field">
            {{ form.description.label }}
            {{ form.description(class = "form-control", placeholder="Description") }}
        </fieldset>
        <fieldset id="fav_song-field">
            {{ form.fav_song.label }}
            {{ form.fav_song(class = "form-control", placeholder="Favorite Song") }}
        </fieldset>
        <fieldset id="artist_rating-field">
            {{ form.artist_rating.label }}
            {{ form.artist_rating(class = "form-control", placeholder="Artist Rating") }}
        </fieldset>
    
        <!-- Submit Button Area -->
        {{ form.submit_button(class = "btn btn-primary btn-block mt-2") }}
    </div>
</form>

pine_sap/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">

<title>Pine Sap API</title>
</head>
<body>

<!-- Nav Bar Below -->
<nav class="ct-nav">
    <div>
        <ul id="horizontal-list">
            <a href="{{ url_for('site.home') }}">
                <li>
                    <img id="navbar_img" src="../static/images/small_pine_logo.png" alt="Pine sap logo">
                </li>
            </a>
            <a href="#">
                <li class="nav_link">Donate</li>
            </a>
            <a href="{{ url_for('site.profile') }}">
                <li class="nav_link">Profile</li>
            </a>
            <a href="#">
                <li class="nav_link">Log Out</li>
            </a>
            <a href="{{ url_for('auth.signin') }}">
                <li class="nav_link">Sign In</li>
            </a>
            <a href="{{ url_for('auth.signup') }}">
                <li class="nav_link">Sign Up</li>
            </a>
        </ul>
    </div>
</nav>

{% block content %}
{% endblock content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

pine_sap/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="username-field">
            {{ form.username.label }}
            {{ form.username(class = "form-control", placeholder = "Place Username Here ...") }}
        </fieldset>
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Place Email Here ...") }}
        </fieldset>
        <fieldset id="password-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place Password Here ...") }}
        </fieldset>
        <!-- submit button -->
        {{ form.submit_buttom(class="btn btn-primary btn-block mt-2") }}
    </div>

</form>